/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed/route'
import { Route as publicRegisterImport } from './routes/(public)/register'
import { Route as publicLoginImport } from './routes/(public)/login'
import { Route as AuthedProblemsIndexImport } from './routes/_authed/problems/index'
import { Route as AuthedProblemsSlugImport } from './routes/_authed/problems/$slug'
import { Route as AuthedProblemsSlugIndexImport } from './routes/_authed/problems/$slug.index'

// Create/Update Routes

const AuthedRouteRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const publicRegisterRoute = publicRegisterImport.update({
  id: '/(public)/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const publicLoginRoute = publicLoginImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthedProblemsIndexRoute = AuthedProblemsIndexImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => AuthedRouteRoute,
} as any)

const AuthedProblemsSlugRoute = AuthedProblemsSlugImport.update({
  id: '/problems/$slug',
  path: '/problems/$slug',
  getParentRoute: () => AuthedRouteRoute,
} as any)

const AuthedProblemsSlugIndexRoute = AuthedProblemsSlugIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedProblemsSlugRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginImport
      parentRoute: typeof rootRoute
    }
    '/(public)/register': {
      id: '/(public)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicRegisterImport
      parentRoute: typeof rootRoute
    }
    '/_authed/problems/$slug': {
      id: '/_authed/problems/$slug'
      path: '/problems/$slug'
      fullPath: '/problems/$slug'
      preLoaderRoute: typeof AuthedProblemsSlugImport
      parentRoute: typeof AuthedRouteImport
    }
    '/_authed/problems/': {
      id: '/_authed/problems/'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof AuthedProblemsIndexImport
      parentRoute: typeof AuthedRouteImport
    }
    '/_authed/problems/$slug/': {
      id: '/_authed/problems/$slug/'
      path: '/'
      fullPath: '/problems/$slug/'
      preLoaderRoute: typeof AuthedProblemsSlugIndexImport
      parentRoute: typeof AuthedProblemsSlugImport
    }
  }
}

// Create and export the route tree

interface AuthedProblemsSlugRouteChildren {
  AuthedProblemsSlugIndexRoute: typeof AuthedProblemsSlugIndexRoute
}

const AuthedProblemsSlugRouteChildren: AuthedProblemsSlugRouteChildren = {
  AuthedProblemsSlugIndexRoute: AuthedProblemsSlugIndexRoute,
}

const AuthedProblemsSlugRouteWithChildren =
  AuthedProblemsSlugRoute._addFileChildren(AuthedProblemsSlugRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedProblemsSlugRoute: typeof AuthedProblemsSlugRouteWithChildren
  AuthedProblemsIndexRoute: typeof AuthedProblemsIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedProblemsSlugRoute: AuthedProblemsSlugRouteWithChildren,
  AuthedProblemsIndexRoute: AuthedProblemsIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthedRouteRouteWithChildren
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRoute
  '/problems/$slug': typeof AuthedProblemsSlugRouteWithChildren
  '/problems': typeof AuthedProblemsIndexRoute
  '/problems/$slug/': typeof AuthedProblemsSlugIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthedRouteRouteWithChildren
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRoute
  '/problems': typeof AuthedProblemsIndexRoute
  '/problems/$slug': typeof AuthedProblemsSlugIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/(public)/register': typeof publicRegisterRoute
  '/_authed/problems/$slug': typeof AuthedProblemsSlugRouteWithChildren
  '/_authed/problems/': typeof AuthedProblemsIndexRoute
  '/_authed/problems/$slug/': typeof AuthedProblemsSlugIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/register'
    | '/problems/$slug'
    | '/problems'
    | '/problems/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/login' | '/register' | '/problems' | '/problems/$slug'
  id:
    | '__root__'
    | '/_authed'
    | '/(public)/login'
    | '/(public)/register'
    | '/_authed/problems/$slug'
    | '/_authed/problems/'
    | '/_authed/problems/$slug/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  publicRegisterRoute: typeof publicRegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  publicRegisterRoute: publicRegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authed",
        "/(public)/login",
        "/(public)/register"
      ]
    },
    "/_authed": {
      "filePath": "_authed/route.tsx",
      "children": [
        "/_authed/problems/$slug",
        "/_authed/problems/"
      ]
    },
    "/(public)/login": {
      "filePath": "(public)/login.tsx"
    },
    "/(public)/register": {
      "filePath": "(public)/register.tsx"
    },
    "/_authed/problems/$slug": {
      "filePath": "_authed/problems/$slug.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/problems/$slug/"
      ]
    },
    "/_authed/problems/": {
      "filePath": "_authed/problems/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/problems/$slug/": {
      "filePath": "_authed/problems/$slug.index.tsx",
      "parent": "/_authed/problems/$slug"
    }
  }
}
ROUTE_MANIFEST_END */
